theme: jekyll-theme-slate
title: Welcome to Wang XinHe's homepage!
description: Fell free to bookmark this to keep an eye on my project updates
github:
  zip_url: https://github.com/Wangxinhe2006/wangxinhe2006.github.io/archive/master.zip
